### ISSUE TITLE
RoadMap 

### ISSUE THREAD

**Issue by JoanaVillanova** [JoanaVillanova/Project-Quote-Generation#2]
## Roadmap
- Phase 1: Product Management
  - [x] Project idea
  - [x] Business Model Canvas
  - [x] Positioning Statement 
  - [x] Information Gathering
- Phase 2: Development 
  - [x] Developments Tools
  - [ ] Early Architectural Skeleton 
- Phase 3: Design/UI/UX
  - [x] Story Board
  - [x] Story Board Update
  - [x] Launch public release
- Phase 4: Quality Assurance (QA)
  - [x] Peer Review 1
  - [x] Coding and Testing Philophy 
  - [x] Peer Review 2
  - [x] Peer Review 3
- Phase 5: Operations/IT
  - [x] Automated deployment pipeline
  - [ ] Pipeline Presentation 
- Phase 6: Marketing and Customer support 
  - [ ] Envisioning presentation 
  - [ ] Speculation presentation 
- Phase 7: Project Management 
  - [x] Project Management (Github)
  - [ ] Roadmap
  - [x] Business Plan
